
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
    - stage: Build
      displayName: Build stage
      jobs:  
      - job: Build
        displayName: Build Maven Project
        steps:
        - task: CmdLine@2
          inputs:
            script: |
              export JAVA_HOME=/opt/sap/sapjvm_17
              System V init distributions: service scc_daemon stop
              systemd distributions: systemctl stop scc_daemon
              System V init distributions: /opt/sap/scc/daemon.sh reinstall
              systemd distributions: /opt/sap/scc/daemon.sh reinstallSystemd
              System V init distributions: service scc_daemon start
              systemd distributions: systemctl start scc_daemon
        - task: Maven@4
          displayName: 'Maven Package'
          inputs:
            mavenPomFile: 'pom.xml'
        - task: CopyFiles@2
          displayName: 'Copy Files to artifact staging directory'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/target/*.?(war|jar)'
            TargetFolder: $(Build.ArtifactStagingDirectory)
        - upload: $(Build.ArtifactStagingDirectory)
          artifact: drop